#!/bin/bash

failed=''

cd bundle
for b in `ls`; do
  pushd $b
  if ([[ -d .git ]] || ([[ -f .git ]] && grep -q "gitdir" .git)); then
    git branch | grep -q develop && git checkout develop || git checkout master
    git pull || failed="$failed $b"
  fi
  popd
done

if [ -n "$failed" ]; then
  echo "Problems updating: $failed"
fi
