#!/bin/bash

let failed=''

cd bundle
for b in `ls`; do
  pushd $b
  if [ -d '.git' ]; then
    git checkout master; git pull || failed="$failed $b"
  fi
  popd
done

if [ -n "$failed" ]; then
  echo "Problems updating: $failed"
fi
